import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

//Components
import Navbar from "../components/Navbar";
import Header from "../components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased lg:h-screen lg:flex flex-col`}
      >
        <Header />

        <div className="flex-1 grid grid-cols-[240px_1fr] overflow-y-hidden">
          <Navbar />

          <div className="overflow-y-scroll">{children}</div>
        </div>
      </body>
    </html>
  );
}
